color: null
description: null
fieldLayouts:
  ef86ffc0-7f77-497f-af7e-3cff4da5960e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-07T22:16:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e51e3b2f-b475-4972-8b4b-6dfcf1c8cc0c # Link (All)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4759f6b-45bb-4f5d-ad11-954c5da7eea0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 23069b6e-7b3b-4cc0-b791-71c04749e773
        userCondition: null
handle: navItem
hasTitleField: false
icon: circle-location-arrow
name: 'Nav Item'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{linkAll.label}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
