color: cyan
description: null
fieldLayouts:
  1b4b46c4-0dcf-4e7e-8598-c699a7ef1e02:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-07T17:30:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 71a17ebd-2e0a-4ac9-93f6-cd221db6c77a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-07T18:23:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 614a0f80-17f1-41dd-bb25-adee56cc18e4 # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c102297-3efd-400e-a504-5a691e19b26b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-07T18:23:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 41218836-6831-49f3-9a90-01aff59d5439 # Image
            handle: featuredImage
            includeInCards: false
            instructions: null
            label: 'Featured Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1585e4ed-4388-46b7-8273-533a86e5757d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-07T18:55:40+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a6d8b248-c057-4a18-a1a1-8699ec65b85d # Article Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6fab76e9-ff44-4110-bdb0-9eea5b4f6361
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-07T20:17:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 39ecbec2-b128-4c74-8dbc-3fc74dd35bb2 # Categories
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 51f4a4dd-9562-46d8-82da-97b40bdcd3c3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 32a2b71f-3027-46f9-859d-8b760cc5d195
        userCondition: null
handle: post
hasTitleField: true
icon: rss
name: Post
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
