color: blue
description: null
fieldLayouts:
  3da83b0b-40e9-412a-99de-bbce34d224ce:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-07T18:51:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e18e51e-c692-4a4c-86b7-8cb0277cfed7 # Text
            handle: quote
            includeInCards: false
            instructions: null
            label: Quote
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a279f2e9-2408-4c0d-8e57-313833ee9021
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-07T18:51:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e18e51e-c692-4a4c-86b7-8cb0277cfed7 # Text
            handle: attribution
            includeInCards: false
            instructions: null
            label: Attribution
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 205dbb54-eb39-4147-a813-73e1c01ece99
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 04f275aa-4200-412e-88e3-840f19f05631
        userCondition: null
handle: pullQuote
hasTitleField: false
icon: comment-quote
name: 'Pull Quote'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
