color: green
description: null
fieldLayouts:
  6ff688e5-373c-4ad9-b8cd-44a9dddfb289:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-07T18:25:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5c9b64ab-8e91-4e96-8fb1-46995f2bc7bd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-07T18:28:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fb83aab5-1f7a-45ae-92a0-7eccc484a135 # Text Card Matrix
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b21b332-9d25-4f69-921e-c935a3f11d70
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f57fad19-065e-4e9b-8aac-d902d32674e0
        userCondition: null
handle: textCards
hasTitleField: true
icon: text
name: 'Text Cards'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
