color: null
description: null
fieldLayouts:
  87e1ee64-564b-4180-a967-cfa57198750f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-07T18:26:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 226dff84-4c5c-4985-9da6-98a51e445511
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-07T18:28:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 614a0f80-17f1-41dd-bb25-adee56cc18e4 # Summary
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36437485-58d5-409c-a81f-441579937a5e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 730b22d3-ae2f-4af1-b618-1b08da2421d0
        userCondition: null
handle: textCard
hasTitleField: true
icon: font
name: 'Text Card'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
