columnSuffix: null
handle: landingPageBuilder
instructions: null
name: 'Landing Page Builder'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - b4e28d0b-ce5e-4141-931a-ee0bf704617d # Title Text
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 7aebea11-377f-4c2b-9044-efcc61c4abcd # Recent Posts
        -
          - group
          - General
    -
      __assoc__:
        -
          - uid
          - 61560819-0798-4b8e-806f-7afd4fe73baf # Text Cards
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
