dateModified: 1756100596
elementSources:
  craft\elements\Asset:
    -
      defaultSort:
        - dateCreated
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'volume:4dff0120-ffae-422b-a9e0-390f0805085d' # Images
      tableAttributes:
        - filename
        - 'fieldInstance:c95237cf-76e2-4dda-831a-3bfa0737756e'
        - size
        - dateModified
        - link
      type: native
    -
      key: temp
      type: native
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Content
      key: 'heading:2988018a-8bd8-4348-b8e5-1f8473e19383'
      type: heading
    -
      key: singles
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:cfb9f183-ae0c-4ff6-b31c-d6b7b819ff1f' # Blog
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:0cac2d6e-2187-4f65-8a40-67b49fe43ae9' # Pages
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Navigation
      key: 'heading:cada9dca-eab5-45f0-acb7-be5dbf78962c'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:2f0f1e53-f4c1-4cfd-ba53-119468ce45bd' # Categories
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:653ca6b8-101d-4124-9d11-7212708f2417' # Navigation
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
email:
  fromEmail: heyitsjenni@gmail.com
  fromName: 'Paradise & Purpose: Sumner Stories'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  imageTransforms:
    hasUrls: true
    name: 'Image Transforms'
    settings:
      path: '@webroot/images/transforms'
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL/images/transforms
  images:
    hasUrls: true
    name: Images
    settings:
      path: '@webroot/images'
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL/images
meta:
  __names__:
    0cac2d6e-2187-4f65-8a40-67b49fe43ae9: Pages # Pages
    2cbe9382-1552-424b-a766-56fe1d597499: Home # Home
    2d4bf084-4122-495b-a4c2-4ed36ec9baa8: 'Paradise & Purpose: Sumner Stories' # Paradise & Purpose: Sumner Stories
    2f0f1e53-f4c1-4cfd-ba53-119468ce45bd: Categories # Categories
    3c4b5c76-5645-4c4d-ac7a-135c514a1be9: 'Listing Page' # Listing Page
    3e18e51e-c692-4a4c-86b7-8cb0277cfed7: Text # Text
    3e35ebe5-8643-4578-8da6-ba8f027efe79: Large # Large
    4dff0120-ffae-422b-a9e0-390f0805085d: Images # Images
    5a7e61d8-fa87-440e-874d-23c9b2f6f7c6: Medium # Medium
    5b4ad86d-b7dd-4f9f-850a-f218f641e4cd: 'Public Schema' # Public Schema
    5f445ac4-2f11-48d5-974a-166f7ba99b9a: 'Newsletter Signup' # Newsletter Signup
    6d17bbfd-6772-48ac-8ac2-8bfda31f7a71: 'Text Card' # Text Card
    7aebea11-377f-4c2b-9044-efcc61c4abcd: 'Recent Posts' # Recent Posts
    7c4084ee-f73f-4bc6-8e28-caab2ca01eb1: Branding # Branding
    8e1c7b9a-c9a7-4527-a3e5-ffac09cfc481: Recirculation # Recirculation
    9deb1b78-d848-4c9a-a26e-ea8416d17c99: 'Pull Quote' # Pull Quote
    39ecbec2-b128-4c74-8dbc-3fc74dd35bb2: Categories # Categories
    341c7907-00f4-49dc-a60e-b185790809d6: Category # Category
    0386d14a-7549-4cf1-964d-a686127a35f3: Image # Image
    614a0f80-17f1-41dd-bb25-adee56cc18e4: Summary # Summary
    653ca6b8-101d-4124-9d11-7212708f2417: Navigation # Navigation
    970a98ef-b8e0-4f47-a481-f9a5445caa7a: 'Image Gallery' # Image Gallery
    2203e170-2325-472d-b713-296a3eeed211: 'Landing Page Builder' # Landing Page Builder
    3705ed95-e2d4-4230-b223-acc8ff4e7283: 'Image Gallery Matrix' # Image Gallery Matrix
    6686249d-c925-4721-bf51-ed5fc9c5e5fb: Images # Images
    41218836-6831-49f3-9a90-01aff59d5439: Image # Image
    61560819-0798-4b8e-806f-7afd4fe73baf: 'Text Cards' # Text Cards
    a6d8b248-c057-4a18-a1a1-8699ec65b85d: 'Article Body' # Article Body
    a7014023-8f58-49ee-aa06-81f4089e04c9: Post # Post
    ac73f4a2-97c5-4432-b1aa-ba7ac8c9c572: 'Home Page' # Home Page
    ae562093-5d8c-49ed-8e0b-92254b62ba7b: Small # Small
    b4e28d0b-ce5e-4141-931a-ee0bf704617d: 'Title Text' # Title Text
    b582f59b-66d7-4ba3-8fd7-8c744ded6cde: Simple # Simple
    bbe4b43a-1686-4439-b500-7215f1d4acf1: 'Blog Listing' # Blog Listing
    c023a841-a229-4b43-809d-1ff2af8816c6: Footer # Footer
    c7e96329-677b-46f3-b962-ea2f6434fb74: 'Another Side of Heaven' # Another Side of Heaven
    c66db33d-32d0-4de9-b66f-7ca99a02814f: Page # Page
    c384dd72-dc07-48ae-8215-67ff80858924: 'Call to Action' # Call to Action
    cfb9f183-ae0c-4ff6-b31c-d6b7b819ff1f: Blog # Blog
    e5beaaff-42ae-49b4-ac91-74e3a12599ef: Hero # Hero
    e51e3b2f-b475-4972-8b4b-6dfcf1c8cc0c: 'Link (All)' # Link (All)
    f5cc05b7-f22f-406d-a1fb-e3ebad4efe88: Post # Post
    f30637bd-6b54-4cd7-8889-2a5b4ef3ba40: 'Nav Item' # Nav Item
    fb83aab5-1f7a-45ae-92a0-7eccc484a135: 'Text Card Matrix' # Text Card Matrix
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: solo
  live: true
  name: 'Another Side of Heaven'
  retryDuration: null
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
