fieldLayouts:
  42073fb4-54c0-42ce-b102-0447b74337d5:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-07T22:33:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e18e51e-c692-4a4c-86b7-8cb0277cfed7 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Footer Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed15096a-7da1-46f1-805c-e0ed9b24ff6b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-07T22:33:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e18e51e-c692-4a4c-86b7-8cb0277cfed7 # Text
            handle: copyright
            includeInCards: false
            instructions: null
            label: Copyright
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b9dc31d3-3044-4f18-9eac-b1db7e361933
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e2347770-d682-4257-aac5-e021246abf76
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
