defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3c4b5c76-5645-4c4d-ac7a-135c514a1be9 # Listing Page
handle: blogListing
maxAuthors: 1
name: 'Blog Listing'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c7e96329-677b-46f3-b962-ea2f6434fb74: # Another Side of Heaven
    enabledByDefault: true
    hasUrls: true
    template: _singles/blog-listing.twig
    uriFormat: blog
type: single
