defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f30637bd-6b54-4cd7-8889-2a5b4ef3ba40 # Nav Item
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  c7e96329-677b-46f3-b962-ea2f6434fb74: # Another Side of Heaven
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 43965a68-2772-4069-bdb5-fb817377b5ad
type: structure
